stages:
  ingest:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/raw/
    outs:
      - ./data/interim/df_cleaned.parquet

  extract_features:
    cmd: python ./src/features/extract_features.py
    deps:
      - ./src/features/extract_features.py
      - ./data/interim/df_cleaned.parquet
      - ./params.yaml
    params:
      - extract_features.mini_batch_kmeans.n_clusters
      - extract_features.mini_batch_kmeans.batch_size
      - extract_features.mini_batch_kmeans.random_state
    outs:
      - ./data/processed/resampled_data.csv
      - ./models/scaler.joblib
      - ./models/mb_kmeans.joblib
  feature_processing:
    cmd: python ./src/features/feature_processing.py
    deps:
      - ./src/features/feature_processing.py
      - ./data/processed/resampled_data.csv
    outs:
      - ./data/processed/train.csv
      - ./data/processed/test.csv
  optuna_tuning:
    cmd: python ./src/models/optuna_tuning.py
    deps:
      - ./src/models/optuna_tuning.py
      - ./data/processed/train.csv
      - ./data/processed/test.csv
    outs:
      - ./models/optuna_hybrid_regionwise_results.csv
  train:
    cmd: python ./src/models/train_model.py
    deps:
      - ./src/models/train_model.py
      - ./data/processed/train.csv
      - ./data/processed/test.csv
      - ./models/optuna_hybrid_regionwise_results.csv
    outs:
      - ./models/training/
  evaluate:
    cmd: python ./src/models/evaluate.py
    deps:
      - ./src/models/evaluate.py
      - ./models/training/
      - ./data/processed/test.csv
    outs:
      - ./models/evaluation/